name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clone Oboe library
        run: |
          rm -rf "Pramod Octapad Pro /app/src/main/cpp/oboe"
          git clone --depth=1 --branch 1.7.0 https://github.com/google/oboe.git "Pramod Octapad Pro /app/src/main/cpp/oboe"

      - name: Clean CMake cache
        run: rm -rf "Pramod Octapad Pro /app/.cxx"

      - name: Grant gradlew permission
        run: chmod +x "Pramod Octapad Pro /gradlew"

      - name: Build Debug APK
        run: cd "Pramod Octapad Pro " && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: "Pramod Octapad Pro /app/build/outputs/apk/debug/*.apk"
