buildscript {
    ext.build_gradle_version = '8.2.0'

    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://clojars.org/repo/" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$build_gradle_version"
        classpath 'com.google.gms:google-services:4.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://clojars.org/repo/" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
